### ISSUE TITLE
Improve UX of "export address" dialog

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/trezor-core#2]
Currently the "export address" (triggered in adalite by "verify on trezor") dialog works as follows:
- title is "export address"
- the address is displayed
- you can either confirm or reject

This probably should be unified with BTC/ETH which do the following:
- the title is the BIP44 path
- you can switch between the address as a string and the QR code and confirm it (there is not really a point in "rejecting" an address)

This can be tried in http://myetherwallet.com ("display address on trezor" when logged in by trezor) and http://trezor.io ("show full address" in "receive" screen)

**Comment by refi93** [comment]
What do you think about this, @ddeath ?

**Comment by ddeath** [comment]
I mean probably it is best for user of trezor to have unified behavior of device and well known flows in apps... On the other hand I was always irritated that the only option how to close it on trezor was just remove the device from PC I was like really mad about it :smile:

**Comment by refi93** [comment]
I see, but I would rather have it unified for now, this should be solved globally and it would be likely easier (if needed at all) to port the solution once it's solved.

**Comment by refi93** [comment]
closed by #1
